// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: campaigns.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCampaign = `-- name: CreateCampaign :one
INSERT INTO campaigns (
    user_id, title, description, status, start_date, end_date, budget
) VALUES (
             $1, $2, $3, $4, $5, $6, $7
         ) RETURNING id, user_id, title, status, budget, created_at
`

type CreateCampaignParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Status      string             `json:"status"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	EndDate     pgtype.Timestamptz `json:"end_date"`
	Budget      float64            `json:"budget"`
}

type CreateCampaignRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	Budget    float64            `json:"budget"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateCampaign(ctx context.Context, arg CreateCampaignParams) (CreateCampaignRow, error) {
	row := q.db.QueryRow(ctx, createCampaign,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.Budget,
	)
	var i CreateCampaignRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Status,
		&i.Budget,
		&i.CreatedAt,
	)
	return i, err
}

const deleteCampaign = `-- name: DeleteCampaign :exec
DELETE FROM campaigns
WHERE id = $1 AND user_id = $2
`

type DeleteCampaignParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteCampaign(ctx context.Context, arg DeleteCampaignParams) error {
	_, err := q.db.Exec(ctx, deleteCampaign, arg.ID, arg.UserID)
	return err
}

const getCampaign = `-- name: GetCampaign :one
SELECT id, user_id, title, description, status, start_date, end_date, budget, created_at, updated_at FROM campaigns
WHERE id = $1 AND user_id = $2
    LIMIT 1
`

type GetCampaignParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetCampaign(ctx context.Context, arg GetCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, getCampaign, arg.ID, arg.UserID)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCampaigns = `-- name: ListCampaigns :many
SELECT id, title, status, start_date, end_date, budget, created_at
FROM campaigns
WHERE user_id = $1
ORDER BY created_at DESC
    LIMIT $2 OFFSET $3
`

type ListCampaignsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

type ListCampaignsRow struct {
	ID        uuid.UUID          `json:"id"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	StartDate pgtype.Timestamptz `json:"start_date"`
	EndDate   pgtype.Timestamptz `json:"end_date"`
	Budget    float64            `json:"budget"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListCampaigns(ctx context.Context, arg ListCampaignsParams) ([]ListCampaignsRow, error) {
	rows, err := q.db.Query(ctx, listCampaigns, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCampaignsRow
	for rows.Next() {
		var i ListCampaignsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Status,
			&i.StartDate,
			&i.EndDate,
			&i.Budget,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCampaign = `-- name: UpdateCampaign :one
UPDATE campaigns
SET
    title = COALESCE($3, title),
    description = COALESCE($4, description),
    status = COALESCE($5, status),
    start_date = COALESCE($6, start_date),
    end_date = COALESCE($7, end_date),
    budget = COALESCE($8, budget),
    updated_at = NOW()
WHERE id = $1 AND user_id = $2
    RETURNING id, user_id, title, description, status, start_date, end_date, budget, created_at, updated_at
`

type UpdateCampaignParams struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Status      string             `json:"status"`
	StartDate   pgtype.Timestamptz `json:"start_date"`
	EndDate     pgtype.Timestamptz `json:"end_date"`
	Budget      float64            `json:"budget"`
}

func (q *Queries) UpdateCampaign(ctx context.Context, arg UpdateCampaignParams) (Campaign, error) {
	row := q.db.QueryRow(ctx, updateCampaign,
		arg.ID,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.StartDate,
		arg.EndDate,
		arg.Budget,
	)
	var i Campaign
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.StartDate,
		&i.EndDate,
		&i.Budget,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
